### ISSUE TITLE
访存量的计算

### ISSUE THREAD

**Issue by Amanda-Barbara** [MrYxJ/calculate-flops.pytorch#10]
这个模块中有访存量的统计计算吗？谢谢。

**Comment by BitCalSaul** [comment]
> 这个模块中有访存量的统计计算吗？谢谢。

请问您找到关于访存量的profiler吗

**Comment by MrYxJ** [comment]
这个工具暂时没有访存量的计算逻辑，理论上通过输入前向传播遍历一遍网络结构访存量也是可以计算出来，感谢您的提醒，之后考虑加上。
