### ISSUE TITLE
flops percent wrong

### ISSUE THREAD

**Issue by Lix1993** [MrYxJ/calculate-flops.pytorch#24]
lamaForCausalLM(
  8.03 B = 100% Params, 30.74 TMACs = 100% MACs, 61.48 TFLOPS = 50% FLOPs

should be 100%，but result is 50%

**Comment by MrYxJ** [comment]
Indeed, this is a print bug that has been fixed in the new version in https://pypi.org/project/calflops/, 0.3.1, you can upgrade this package to get the latest version, Thank you for pointing out the error.

```
pip install calflops==0.3.1
```
