### ISSUE TITLE
Is it considering output length of transformer models?

### ISSUE THREAD

**Issue by liut89** [MrYxJ/calculate-flops.pytorch#25]
I think the result FLOPs and MACs are influenced not only by input length but also output length, I'm I right?
If yes, is the tool considering out put length? How to control the output length?

**Comment by MrYxJ** [comment]
Of course, it is relevant. The calculation of FLOPs here strictly defaults to the calculation amount of the prefill phase of the model, which can be regarded as the default output of a token.
