### ISSUE TITLE
why I can not find transformers.modeling_outputs,Can you tell me your vision of transformers

### ISSUE THREAD

**Issue by kingofengineer** [MrYxJ/calculate-flops.pytorch#9]
---> 32     from transformers.modeling_outputs import (
     33         CausalLMOutputWithCrossAttentions,
     34         Seq2SeqLMOutput,
     35         SequenceClassifierOutput,
     36     )
ModuleNotFoundError: No module named 'transformers.modeling_outputs'

**Comment by MrYxJ** [comment]
I recommend vision of transformers >= 4.34.0
